### ISSUE TITLE
Order/Chaos guild notosend problem.

### ISSUE THREAD

**Issue by Nefrelius** [Sphereserver/Source-X#1094]
When guilds choose sides, those who choose the order/chaos support direction don't appear orange to each other, the same way chaos/chaos guilds don't appear green to each other. Only members of the same guild appear green and guilds that are at war appear orange.
![iaamage](https://github.com/Sphereserver/Source-X/assets/121174463/64d53320-92b5-4eeb-8403-23c04ff909dd)
![image](https://github.com/Sphereserver/Source-X/assets/121174463/43a54621-31a7-425d-b96d-3110d55e9cf5)

**Comment by LuxionUO** [comment]
This should be fixed now with the commit: #1091 

You can download Sphere and test it, remember that you need to activate the optionFlag on Sphere.ini.

**Comment by AtillaG1** [comment]
I think its not fixed, since from what I remember, If you are align Chaos or Order, now you can see neutral players as orange "NOTORIETY" which is enemy, but should be blue - neutral.

**Comment by Nefrelius** [comment]
This has not been fully corrected. If the guild chooses either order or chaos, neutral guilds also appear orange. Actually Order/Chaos should be direct enemies and Order/Order should see green. Neutral guilds should not be involved in this notosend thing at all if there is no declaration of war. (deepl)

**Comment by AtillaG1** [comment]
> and Order/Order should see green. 
I feel like this part would be good to have possibility to switch if green or blue....
