### ISSUE TITLE
Combat problem and monster stay in WAR

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#517]
OK here the problem.
We had all monster always stay in WAR . This bug was fix in this issue:
https://github.com/Sphereserver/Source-X/issues/377

Julian Revert the commit for fixing new stuff and made a better fix
https://github.com/Sphereserver/Source-X/issues/409

There a situation where NPC stay In war but i'm not able to reproduce it for now

So at this time, lot of NPC stay in War mode.

**Comment by Jhobean** [comment]
ok here you go how reproduce it:
.go Despise or anywhere you can flee in a door
.add c_zombie
remove your invul flag and wait you see the emote "Zombie is attacking you"
Don't be hit by the zombie and run away.

Come back later invisible and look their flag.. All stuck to WARMODE

**Comment by drk84** [comment]
I did some test and i  think the bug is caused when the memory item timer on the NPC expires before the NPC's attacker.n.elapsed property reach AttackerTimeout.

If the memory item timer expires first, the npc action becomes NPCACT_WANDER and so it will not enter anymore in Fight_HitTry method where the clearing of the War flag happens.

By default the memory item timer is created with a timer value of 300 seconds and the default AttackerTimeOut setting is 300 seconds.

**Comment by drk84** [comment]
This seems fixed with the previous timer builds

**Comment by drk84** [comment]
Have some reports that is not fixed, i'll check more

**Comment by Soulless-1** [comment]
can confirm that I still see some npcs in war mode for no reason around the map.

**Comment by Jhobean** [comment]
Yep.. 
![image](https://user-images.githubusercontent.com/51728381/133947134-db909fbe-a927-4073-9bfe-5ca71a8cc725.png)

no reason to be in war mode

**Comment by Soulless-1** [comment]
I never find any memories or attackers in attacker list, its just has statf_war for no reason

**Comment by Tolokio** [comment]
could be fix it doing that if an npc start "NPCACT_WANDER" war status is removed?

**Comment by Jhobean** [comment]
Maybe... Give it a try. But npc wander in war mode?

**Comment by Tolokio** [comment]
drk said npc with blocked war status start "npcact_wander" if it is not a "bug" caused by bad code, it could be a good place to do the fix.
![image](https://user-images.githubusercontent.com/20745578/197083983-02c41570-da15-4e7a-a8c9-98019da4d567.png)
Even if the code is broken, this way could be less bad for performance. I dont know....
IS the problem located 100% in the code?

**Comment by xwerswoodx** [comment]
I am testing in current build and seems like when the memory item removed the war mode automatically cleaning. Are you sure this is still an issue? Can you reproduce it, if it still an issue

ok here you go how reproduce it:
.go Despise or anywhere you can flee in a door
.add c_zombie
remove your invul flag and wait you see the emote "Zombie is attacking you"

I tried that exactly, but I can test it couple of more times tomorrow.

**Comment by xwerswoodx** [comment]
Should be fixed now.

**Comment by Jhobean** [comment]
Mervellous!  Work. Big thx!
