### ISSUE TITLE
on server close

### ISSUE THREAD

**Issue by youhide** [Sphereserver/Source-X#552]
17:19:(sphere_serv_triggers.scp,186)Statics data saved (save/spherestatics.scp).
17:19:Garbage Collection: started.
17:19:Garbage Collection: done. 116435 Objects accounted for.
17:19:World data saved   (save/sphereworld.scp).
17:19:Player data saved  (save/spherechars.scp).
17:19:Multi data saved   (save/spheremultis.scp).
17:19:Context data saved (save/spheredata.scp).
17:19:World save completed, took 1.9230 seconds.
17:19:Secure mode disabled.
17:19:FATAL:Immediate Shutdown initialized!
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +864302  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +2066  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +1  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +2 <-- last function call (stack unwinding began here)
17:19:CRITICAL:Generic exception, in ExcType=pure catched in CSObjCont::Deleting objects scheduled for deletion()
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +989790  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +2924  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +2 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +1146  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +0 <-- last function call (stack unwinding began here)
17:19:CRITICAL:Generic exception, in ExcType=pure catched in CSObjCont::Deleting objects scheduled for deletion()
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +1786  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +2 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +2730  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +1 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +20534  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +7 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +36371  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +1  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +1 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +52004  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +1  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +5 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +52693  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +2 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +53321  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +5 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +53921  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +1  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +2 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +72487  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +1  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +1 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +73231  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +1 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +89562  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +1  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +1 <-- last function call (stack unwinding began here)
17:19:DEBUG:Printing STACK TRACE for debugging purposes.
17:19:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
17:19:DEBUG:(02620)        T_Net #0 |  0 |                        CWorld::Close | +0  
17:19:DEBUG:(02620)        T_Net #0 |  1 |                   CSectorList::Close | +158  
17:19:DEBUG:(02620)        T_Net #0 |  2 |                       CSector::Close | +1292075  
17:19:DEBUG:(02620)        T_Net #0 |  3 |                        CItem::~CItem | +106061  
17:19:DEBUG:(02620)        T_Net #0 |  4 |                 CItem::DeleteCleanup | +0  
17:19:DEBUG:(02620)        T_Net #0 |  5 |               CItemMulti::UnlockItem | +1 <-- last function call (stack unwinding began here)
17:19:FATAL:Server terminated: X command on console (code 1)

**Comment by Nirad** [comment]
on linux ?

**Comment by xwerswoodx** [comment]
Can you check your scripts that includes UNLOCKITEM command.

**Comment by youhide** [comment]
on windows, just the house sys from x script pack use this unlock

**Comment by xwerswoodx** [comment]
What is the result after nolok's update?

**Comment by youhide** [comment]
13:24:1:'youri' commands 'remove'=1
13:24:DEBUG:Printing STACK TRACE for debugging purposes.
13:24:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
13:24:DEBUG:(09036)          T_Main |  0 |     CNetworkManager::processAllInput | +0  
13:24:DEBUG:(09036)          T_Main |  1 |          CNetworkInput::processInput | +2172  
13:24:DEBUG:(09036)          T_Main |  2 |           CNetworkInput::processData | +4538  
13:24:DEBUG:(09036)          T_Main |  3 |           CNetworkInput::processData | +3  
13:24:DEBUG:(09036)          T_Main |  4 | CNetworkInput::processGameClientData | +1  
13:24:DEBUG:(09036)          T_Main |  5 |              PacketTarget::onReceive | +6  
13:24:DEBUG:(09036)          T_Main |  6 |                CClient::Event_Target | +1  
13:24:DEBUG:(09036)          T_Main |  7 |              CClient::OnTarg_Obj_Set | +5  
13:24:DEBUG:(09036)          T_Main |  8 |               CItemContainer::r_Verb | +35  
13:24:DEBUG:(09036)          T_Main |  9 |                        CItem::r_Verb | +1  
13:24:DEBUG:(09036)          T_Main | 10 |                     CObjBase::r_Verb | +2  
13:24:DEBUG:(09036)          T_Main | 11 |                        CItem::Delete | +3  
13:24:DEBUG:(09036)          T_Main | 12 |                 CItem::DeleteCleanup | +61026  
13:24:DEBUG:(09036)          T_Main | 13 |               CItemMulti::UnlockItem | +3 <-- last function call (stack unwinding began here)
13:24:CRITICAL:"Access Violation" (0x7aea4), in ExcType=CSError catched in CObjBase::Verb() #1 "REMOVE"
13:24:DEBUG:command 'remove' args '' [0000019C951A4080]

when trying to remove lock item... sometimes GC crash spheres with misslinked locked item

**Comment by xwerswoodx** [comment]
System changed a bit yesterday, there could be some problems, it will be fixed in next couple of commits.

**Comment by youhide** [comment]
> System changed a bit yesterday, there could be some problems, it will be fixed in next couple of commits.

lemme test it

**Comment by youhide** [comment]
13:31:1:'youri' commands 'remove'=1
13:31:DEBUG:Printing STACK TRACE for debugging purposes.
13:31:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
13:31:DEBUG:(07436)          T_Main |  0 |                CNetworkManager::tick | +0  
13:31:DEBUG:(07436)          T_Main |  1 |                 CNetworkThread::tick | +17  
13:31:DEBUG:(07436)          T_Main |  2 |          CNetworkInput::processInput | +2  
13:31:DEBUG:(07436)          T_Main |  3 |           CNetworkInput::processData | +6370  
13:31:DEBUG:(07436)          T_Main |  4 |           CNetworkInput::processData | +29  
13:31:DEBUG:(07436)          T_Main |  5 | CNetworkInput::processGameClientData | +1  
13:31:DEBUG:(07436)          T_Main |  6 |              PacketTarget::onReceive | +99  
13:31:DEBUG:(07436)          T_Main |  7 |                CClient::Event_Target | +27  
13:31:DEBUG:(07436)          T_Main |  8 |              CClient::OnTarg_Obj_Set | +82  
13:31:DEBUG:(07436)          T_Main |  9 |               CItemContainer::r_Verb | +47  
13:31:DEBUG:(07436)          T_Main | 10 |                        CItem::r_Verb | +1  
13:31:DEBUG:(07436)          T_Main | 11 |                     CObjBase::r_Verb | +3  
13:31:DEBUG:(07436)          T_Main | 12 |                        CItem::Delete | +3  
13:31:DEBUG:(07436)          T_Main | 13 |                 CItem::DeleteCleanup | +92241  
13:31:DEBUG:(07436)          T_Main | 14 |               CItemMulti::UnlockItem | +3 <-- last function call (stack unwinding began here)
13:31:CRITICAL:"Access Violation" (0x7b450), in ExcType=CSError catched in CObjBase::Verb() #1 "REMOVE"
13:31:DEBUG:command 'remove' args '' [000001AE56956070]
13:31:'youri' commands uid=040006a91 (secret chest) to 'remove'=0
13:32:(n_workerman.scp,24)Legend Worker Man is checking world lamps
13:32:(sphere_serv_triggers.scp,184)Statics data saved (save/spherestatics.scp).
13:32:Garbage Collection: started.
13:32:ERROR:GC: Deleted UID=040006a91, Defname='i_chest_secret', Name='secret chest'. Invalid code=0x3101 (Object is totally lost, no parent exists).
13:32:DEBUG:Printing STACK TRACE for debugging purposes.
13:32:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | microseconds passed from previous function start
13:32:DEBUG:(07436)          T_Main |  0 |                      CServer::OnTick | +0  
13:32:DEBUG:(07436)          T_Main |  1 |                CServer::OnConsoleCmd | +8  
13:32:DEBUG:(07436)          T_Main |  2 |                      CServer::r_Verb | +27  
13:32:DEBUG:(07436)          T_Main |  3 |                         CWorld::Save | +7  
13:32:DEBUG:(07436)          T_Main |  4 |                      CWorld::SaveTry | +341021  
13:32:DEBUG:(07436)          T_Main |  5 |            CWorld::GarbageCollection | +1  
13:32:DEBUG:(07436)          T_Main |  6 | CWorldThread::GarbageCollection_UIDs | +67  
13:32:DEBUG:(07436)          T_Main |  7 |                 CWorldThread::FixObj | +30357  
13:32:DEBUG:(07436)          T_Main |  8 |                        CItem::Delete | +181  
13:32:DEBUG:(07436)          T_Main |  9 |                 CItem::DeleteCleanup | +18  
13:32:DEBUG:(07436)          T_Main | 10 |               CItemMulti::UnlockItem | +4 <-- last function call (stack unwinding began here)
13:32:CRITICAL:"Access Violation" (0x7b450), in UID=040006a91, Asserted cleanup
13:32:Garbage Collection: done. 121019 Objects accounted for.

**Comment by youhide** [comment]
no crash anymore

13:34:(sphere_serv_triggers.scp,184)Statics data saved (save/spherestatics.scp).
13:34:Garbage Collection: started.
13:34:ERROR:'steam powered beverage maker' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040006a85, Defname='i_steam_powered_beverage_maker', Name='steam powered beverage maker'. Invalid code=0x2205 (Mislinked item).
13:34:CRITICAL:"Access Violation" (0x7b450), in UID=040006a85, Asserted cleanup
13:34:ERROR:'alchemist bookcase' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040006a92, Defname='i_bookcase_alchemist', Name='alchemist bookcase'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'forge' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040006aa0, Defname='i_forge', Name='forge'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'decorative shield' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040009a99, Defname='i_decorative_shield_6', Name='decorative shield'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'tinker bench' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000abc8, Defname='i_tinker_bench', Name='tinker bench'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'enchanted writing desk' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000acb0, Defname='i_enchanted_writing_desk', Name='enchanted writing desk'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'BBQ smoker' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000acf9, Defname='i_bbq_smoker_cont', Name='BBQ smoker'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'alchemy station' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000b25f, Defname='i_alchemy_station', Name='alchemy station'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'fletching station' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000b3f4, Defname='i_fletching_station', Name='fletching station'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'sewing machine' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000b671, Defname='i_sewing_machine', Name='sewing machine'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000be9c, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000eaec, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000eaef, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:CRITICAL:"Access Violation" (0x7b450), in UID=04000eaef, Asserted cleanup
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000eb4c, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000eb4e, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000eb50, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000eb51, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'chaos banner' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000ecfe, Defname='i_banner_chaos', Name='chaos banner'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'metal chest' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04000fc19, Defname='i_chest_metal', Name='metal chest'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040010904, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'cowbell' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040011be8, Defname='i_cowbell', Name='cowbell'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'cello' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040011d36, Defname='i_cello', Name='cello'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'castle painting' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001209d, Defname='i_painting_castle', Name='castle painting'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:GC: Deleted UID=040012152, Defname='i_pet_dragon_crimson', Name='Crimson Dragon'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:GC: Deleted UID=0400134c3, Defname='i_pet_dragon_platinum', Name='Platinum Dragon'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:'confetti cannon' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040016542, Defname='i_confetti_cannon', Name='confetti cannon'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'japanese maple' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001659d, Defname='i_japanese_maple', Name='japanese maple'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'metal chest' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400167c8, Defname='i_chest_metal', Name='metal chest'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017068, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017087, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001708e, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001709c, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001709d, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170a3, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170b0, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170b1, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170bf, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170c2, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170e4, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170e6, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170ef, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170f5, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170f8, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=0400170fb, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017107, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001710c, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001711a, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001711c, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017132, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017133, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017135, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001713a, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017166, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017182, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:CRITICAL:"Access Violation" (0x7b450), in GarbageCollection_UIDs
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=040017199, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:'dyeing tub' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001719b, Defname='i_dye_tub', Name='dyeing tub'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:GC: Deleted UID=04001a221, Defname='i_talisman_tinker', Name='Talisman of Tinker'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:GC: Deleted UID=04001c1e0, Defname='i_ingot_Platinum', Name='Platinum Ingot'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:GC: Deleted UID=04001c1e3, Defname='i_ingot_Tantalio', Name='Tantalio Ingot'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:GC: Deleted UID=04001c1e5, Defname='i_ingot_Adamantium', Name='Adamantium Ingot'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:'jukari tribal banner' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001c3ea, Defname='i_banner_tribal_jukari', Name='jukari tribal banner'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:GC: Deleted UID=04001cd14, Defname='i_backpack', Name='backpack'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:'mailbox' Bad Link to 04000bd1f
13:34:ERROR:GC: Deleted UID=04001d96b, Defname='i_mailbox_s', Name='mailbox'. Invalid code=0x2205 (Mislinked item).
13:34:ERROR:GC: Deleted UID=04001da63, Defname='i_potion_shrink', Name='Shrink Potion'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:GC: Deleted UID=04001da73, Defname='i_potion_shrink', Name='Shrink Potion'. Invalid code=0x2104 (Disconnected item).
13:34:ERROR:Garbage Collection: done. Object memory leak 121021!=120998.
13:34:World data saved   (save/sphereworld.scp).
13:34:Player data saved  (save/spherechars.scp).
13:34:Multi data saved   (save/spheremultis.scp).
13:34:Context data saved (save/spheredata.scp).
13:34:World save completed, took 2.4390 seconds.

**Comment by xwerswoodx** [comment]
Thank you for information, but if you write what causes the issue top of the message it could be nice. Like;

When I removed X item from multi without unlock item it causes;
```
DEBUG- bla bla
bla bla bla
bla bla bla
```

**Comment by youhide** [comment]
lockitem -> delete house -> save
and
lockitem -> delete house -> try remove

now im getting this behavior on last update when i dclick on something inside house
![image](https://user-images.githubusercontent.com/4053124/103099836-ca177500-45ee-11eb-826e-5385bd483ccd.png)

**Comment by xwerswoodx** [comment]
@youhide can you check if the issues still occur after latest update?

**Comment by youhide** [comment]
multi seems to have fixed
now im getting error on owner check for pet
`IF (<OWNER>)`
`Can't resolve <OWNER>`

**Comment by Jhobean** [comment]
@youhide same

**Comment by xwerswoodx** [comment]
@youhide where are you checking that? Can you give me an example, because I am trying;

```
[FUNCTION ow]
IF (<OWNER>)
  RETURN <OWNER>
ENDIF
RETURN 0xfff
```

And seems like working fine for me.

**Comment by youhide** [comment]
im using on
ON=@NPCLookAtChar
IF (<OWNER>)

ill try this workaround

**Comment by youhide** [comment]
another strange error
ERROR:(sphere_region.scp,632)Can't resolve <SRC.REGION.TAG.MUSIC>

**Comment by youhide** [comment]
same for ipet memory
14:53:ERROR:(e_pet_ai.scp,222)Can't resolve <MEMORYFINDTYPE.memory_ipet>

**Comment by youhide** [comment]
> Edit: Seems like if the pet don't have owner, that causes it.
> 
> ```
> IF (<MEMORYFINDTYPE.memory_ipet>)
> ```
> 
> Solve your issue temporarily. Is this issue happen after update?

yes, after this update!

**Comment by xwerswoodx** [comment]
I see, we are currently talking about the issue, we are already know what causes the issue, it's not a big idea but it will be fixed in short 👍

**Comment by alexdan2** [comment]
> I see, we are currently talking about the issue, we are already know what causes the issue, it's not a big idea but it will be fixed in short 👍

Perfect i starting to open new issue but i see here ppl already discussion here, i can confirm in last release some Can't resolve

**Comment by cbnolok** [comment]
It should be fixed now

**Comment by alexdan2** [comment]
> It should be fixed now

Can't resolv problem seems not fixed. 
I opened new issue for make it more clear (https://github.com/Sphereserver/Source-X/issues/580)
