### ISSUE TITLE
@Timer trigger on t_eq_script freezes X

### ISSUE THREAD

**Issue by GorGoUO** [Sphereserver/Source-X#649]
Using 14/3/21 nightly of SphereX (64bits), server freezes when an equiped memory of t_eq_script type calls @timer trigger. In my case, nomind the code lines that trigger has, even with a simple timer=10 and return 1 freezes server and client.

With this seems to work fine: [https://ci.appveyor.com/project/cbnolok/sphereserver-x/builds/38068128/job/dv63qkq3ur4goaks/artifacts](url)

Hope this help, thank you for your hard work.

**Comment by cbnolok** [comment]
Try with latest build!

**Comment by GorGoUO** [comment]
New build still crashing. This is the script:

`[Function New_Poison]

//Prevent Poison to Poisonous monsters, undead and npcs with respoison at 100 or more
If ((<Npc>) && (((<Poisonous>) && (<DEF0.PoisonSys_MonsterImmunePoisonous>)) || ((<Brain>==brain_undead) && (<DEF0.PoisonSys_MonsterImmuneUndead>)) || ((<ResPoison> >= 100) && (<DEF0.PoisonSys_MonsterImmuneResist>))))
	Message @,,2 <Def0.PoisonCliloc_PoisonImmune>
	Return 1
Endif

Local.Poison = <Eval <Argv[0]>>
//evil omen
if <isevent.e_evil_omen>
	local.poison +1
	if (<dlocal.poison> > 4)
		local.poison=4
	endif
	removebuff <def0.bufficon_evilomen>
	sysmessage @msg_<skillclass> Las Fuerzas Oscuras aumentan la potencia del veneno!
	if <tag0.magicresistance_evil_omen>
		magicresistance=<tag0.magicresistance_evil_omen>
		tag.magicresistance_evil_omen=
	endif
	events -e_evil_omen
endif
If !<Isempty <Argv[1]>>
	Local.Src = <Argv[1]>
Else
	Local.Src = <Uid>
Endif
If <Findid.i_memory_poison_new>
	If <Findid.i_memory_poison_new.More2> > <Local.Poison>
		Return 1
	Elif <Findid.i_memory_poison_new.More2> == <Local.Poison>
		Findid.i_memory_poison_new.More1h = <Def0.PoisonType_<dLocal.Poison>_Duration>
		Return 1
	Else
		Consume i_memory_poison_new
	Endif
Endif
Serv.Newitem = i_memory_poison_new
New.More2 = <Local.Poison>
New.Link = <Local.Src>
New.More1l = <Def0.PoisonType_<dLocal.Poison>_Frequency>
New.More1h = <Def0.PoisonType_<dLocal.Poison>_Duration>
If <Trigger @Poison,<Def0.TAT_AS_ARGO>,<New.Uid>> == 1
	New.Remove
elif <isevent.e_vampire>
	if <new.more2> < 5
		new.remove
		sysmessage @msg_<skillclass> Eres inmune al veneno
		src.sysmessage @msg_<src.skillclass> <name> es inmune al veneno
	endif
Else
	Equip <New.Uid>
	if (<dlocal.poison> = 4)
		local.cliloc2=1054026
	else
		local.cliloc2=<eval (1054015+<dlocal.poison>)>
	endif
	if <isplayer>
		addbuff <def0.bufficon_poison>,<def0.buffcliloc_poison_1>,<dlocal.cliloc2>,<new.more1h>,0
	endif
endif


[Itemdef i_memory_poison_new]
ID=i_memory
TYPE=t_eq_script
NAME=Poison

ON=@Equip
Timer = <More1l>
Src.Flags = <Src.Flags>|080
Src.Update
Src.Sysmessage @,,2 <Def0.PoisonCliloc_BeenPoisoned>
If (<Cont.IsPlayer>)
   TrySrc <Cont> Cont.Message @32,,2 <Def0.PoisonType_<dMore2>_Message_Self>
Endif
If ((<Cont.Flags> != <Cont.Flags>|08) && (<Cont.Flags> != <Cont.Flags>|0800000))
   Cont.f_Psn_msg_other <dMore2>
Endif
Src.Events +e_poisoned
Morex = <Eval 1 + (<Src.Hits> / <Def0.PoisonType_<Eval <More2>>_Divide>)>
Morex = <PsnSys_Max <Morex>,<Def0.PoisonType_<Eval <More2>>_DamLow>>
Morex = <PsnSys_Min <Morex>,<Def0.PoisonType_<Eval <More2>>_DamHigh>>
If !<IsEmpty <Def.PoisonType_<Eval <More2>>_Function>>
Src.<Def.PoisonType_<Eval <More2>>_Function> 1
Endif

ON=@Unequip
Src.Flags = <Src.Flags>&~080
Src.Update
Src.Events -e_poisoned
if <src.isplayer>
	src.removebuff 1038
	If <Tag0.Cured>
		Src.Sysmessage @,,2 <Def0.PoisonCliloc_BeenCured>
	endif
Endif

ON=@Cure
Tag.Cure = <Argn1>
Local.Cure = <Cont.Trigger @Cure,<Def0.TAT_AS_ARGO>,<Uid>>
If <Local.Cure>==-1
Tag.Cured = 1
Remove
Return 1
Endif
If ((<Local.Cure>==2) || (<Local.Cure>==0))
If Rand(1,<Def0.PoisonType_<Eval <More2>>_Difficulty>) < <Tag0.Cure>
Tag.Cured = 1
Remove
Return 1
Endif
Return 0
Endif
Return 0

On=@Timer
If ((!<Link.IsChar>) && (!<Link.IsItem>))
Link = <Cont.Uid>
Endif

If <Cont.Trigger @PoisonTick,<Def0.TAT_AS_ARGO>,<Uid>> == 1
Remove
Return 1
Endif

More1h -= <More1l>

//Damage Calculation
If RAND(1,100) <= <Def0.PoisonType_<Eval <More2>>_RecalcChance>
Morex = <Eval 1 + (<Cont.Hits> / <Def0.PoisonType_<Eval <More2>>_Divide>)>
Morex = <PsnSys_Max <Morex>,<Def0.PoisonType_<Eval <More2>>_DamLow>>
Morex = <PsnSys_Min <Morex>,<Def0.PoisonType_<Eval <More2>>_DamHigh>>
Endif

If !<IsEmpty <Def.PoisonType_<Eval <More2>>_Function>>
Cont.<Def.PoisonType_<Eval <More2>>_Function> 0
Endif

//Timer Check & Set
If <More1h> <= 0
Cont.Sysmessage @,,2 <Def0.PoisonCliloc_WornOff>
Remove
return 1
Else
Timer = <More1l>
Endif

//Damage (Poison, Noreveal)
local.damage=<morex>
local.damage -=<percent <cont.tag0.efecto_veneno>,<morex>>
Cont.Damage <dlocal.damage> 04008 <Link.Uid>

//Message (Message if hidden, Say if not)
If (<Cont.IsPlayer>)
   TrySrc <Cont> Cont.Message @32,,2 <Def0.PoisonType_<dMore2>_Message_Self>
Endif
If ((<Cont.Flags> != <Cont.Flags>|08) && (<Cont.Flags> != <Cont.Flags>|0800000))
   Cont.f_Psn_msg_other <dMore2>
Endif

Return 1`

With the build I posted before works perfectly, but with last build server freezes when @timer. Thanks.

**Comment by cbnolok** [comment]
Can you please fix the quotes? There are missing parts on the script

**Comment by cbnolok** [comment]
Never mind, found the problem

**Comment by GorGoUO** [comment]
It seems to work ok now. Thank you!

**Comment by GorGoUO** [comment]
I don´t know if it´s the same problem, but now @timer does not activate. Tried with this test script:

```[FUNCTION f_test]
damage 2 04008 //dam works OK here
serv.newitem=i_delay_dam
new.timer=2
new.cont=<uid>

[ITEMDEF i_delay_dam]
ID=i_memory
TYPE=t_eq_script

ON=@TIMER //timer goes -1 and not activate @timer trigger, no effect
cont.damage 2,04008
timer=2
return 1```

**Comment by cbnolok** [comment]
It should be fixed now

**Comment by GorGoUO** [comment]
Still freezing sphere but now not on @timer but cont.damage 2,04008. Maybe that new error is in my scripts? The damage of the function f_test works for me, but not cont.damage. Thanks.

**Comment by cbnolok** [comment]
What about now?

**Comment by GorGoUO** [comment]
Still freezing when runs cont.damage. I hope someone test my script for ensure that isn't a particular problem in my server.

**Comment by alexdan2** [comment]
> I don´t know if it´s the same problem, but now @Timer does not activate. Tried with this test script:
> 
> ```
> [FUNCTION f_test]
> damage 2 04008 //dam works OK here
> serv.newitem=i_delay_dam
> new.timer=2
> new.cont=<uid>
> 
> [ITEMDEF i_delay_dam]
> ID=i_memory
> TYPE=t_eq_script
> 
> ON=@TIMER //timer goes -1 and not activate @timer trigger, no effect
> cont.damage 2,04008
> timer=2
> return 1```
> ```

I tested this function but not have any issue :(

**Comment by xMirroRx** [comment]
With version 3419, @timer was not firing. I tested it with the latest version, there is no problem.

**Comment by GorGoUO** [comment]
OK as I said before now @Timer appears to run correctly. I still have cont.damage problem that freezes the server, but I could assume that is a particular issue, maybe my scripts. Nobody else that tested my function has the same problem?

Thank you nolok for solve timer issues.

**Comment by xMirroRx** [comment]
> [FUNCTION f_test]
> damage 2 04008 //dam works OK here
> serv.newitem=i_delay_dam
> new.timer=2
> new.cont=<uid>
> 
> [ITEMDEF i_delay_dam]
> ID=i_memory
> TYPE=t_eq_script
> 
> ON=@TIMER //timer goes -1 and not activate @timer trigger, no effect
> cont.damage 2,04008
> timer=2
> return 1```

I can only say that I have no problems with this coding. I have no freezing problem.

**Comment by GorGoUO** [comment]
OK I think the damage problem is only mine. @Timer is working perfectly. Thanks again.
